### connect physical hardware to abstract test ports
POST {{host}}/restconf/data/openhltest-session:session=regression-1/config/connect-ports
Content-Type: application/json

{
	"input": [
		{
			"port-name": "PE-1/1",
			"chassis": "10.36.74.53",
			"card": 6,
			"port": 2
		},
		{
			"port-name": "PE-1/2",
			"chassis": "10.36.74.53",
			"card": 7,
			"port": 2
		}
	]
}

### start all protocols
POST {{host}}/restconf/data/openhltest-session:session=regression-1/config/start-protocols
Content-Type: application/json

{
	"input": []
}

### clear all statistic counters
POST {{host}}/restconf/data/openhltest-session:session=regression-1/statistics/clear-statistics

### start all traffic
POST {{host}}/restconf/data/openhltest-session:session=regression-1/config/start-traffic
Content-Type: application/json

{
	"input": []
}

