### get a list of sessions
GET {{host}}/restconf/data/openhltest-session:session?depth=1

### get a session by name
GET {{host}}/restconf/data/openhltest-session:session=regression-1?depth=1

### create a session
POST {{host}}/restconf/data
Content-Type: application/json

{
	"openhltest-session:session": {
		"name": "regression-2",
		"session-type": "L2L3"
	}
}

### delete a session
DELETE {{host}}/restconf/data/openhltest-session:session=regression-1



