### create a traffic port stream
POST {{host}}/restconf/data/oht:session=regression-1/config
Content-Type: application/json

{
	"openhltest-ports:ports": [
		{
			"name": "PE-2/7",
			"location": "10.36.74.53/1/1"
		}
	],
	"openhltest-traffic-ports:port-traffic": [
		{
			"name": "Port Stream 1",
			"source": "../ports/name=PE-2/7",
			"destinations": [],
			"frames": [
				{
					"name": "Ethernet 1",
					"frame-type": "ETHERNET",
					"ethernet": {
						"destination": {
							"pattern-type": "SINGLE",
							"single": "00:00:00:00:00:01"
						},
						"source": {
							"pattern-type": "INCREMENT",
							"start": "00:00:01:00:00:01",
							"step": "00:00:00:00:00:01",
							"count": 10,
							"use-stream": true
						},
						"ethernet-type": {
							"pattern-type": "SINGLE",
							"single": "88B5"
						}
					}
				}
			],
			"frame-length": {
				"length-type": "FIXED",
				"fixed": 128
			},
			"frame-rate": {
				"rate-type": "PERCENT_LINE_RATE",
				"percent-line-rate": "20"
			}
		}
	]
}